#include <SDL/SDL.h>
#include <goomba/key.h>

static const char *key_name_backspace = "Backspace";
static const char *key_name_tab = "Tab";
static const char *key_name_clear = "Clear";
static const char *key_name_return = "Return";
static const char *key_name_pause = "Pause";
static const char *key_name_escape = "Esc";
static const char *key_name_space = "Space";
static const char *key_name_exclaim = "!";
static const char *key_name_quotedbl = "\"";
static const char *key_name_hash = "#";
static const char *key_name_dollar = "$";
static const char *key_name_ampersand = "&";
static const char *key_name_quote = "\'";
static const char *key_name_leftparen = "(";
static const char *key_name_rightparen = ")";
static const char *key_name_asterisk = "*";
static const char *key_name_plus = "+";
static const char *key_name_comma = ",";
static const char *key_name_minus = "-";
static const char *key_name_period = ".";
static const char *key_name_slash = "/";
static const char *key_name_0 = "0";
static const char *key_name_1 = "1";
static const char *key_name_2 = "2";
static const char *key_name_3 = "3";
static const char *key_name_4 = "4";
static const char *key_name_5 = "5";
static const char *key_name_6 = "6";
static const char *key_name_7 = "7";
static const char *key_name_8 = "8";
static const char *key_name_9 = "9";
static const char *key_name_colon = ":";
static const char *key_name_semicolon = ";";
static const char *key_name_less = "<";
static const char *key_name_equals = "=";
static const char *key_name_greater = ">";
static const char *key_name_question = "?";
static const char *key_name_at = "@";
static const char *key_name_leftbracket = "[";
static const char *key_name_backslash = "\\";
static const char *key_name_rightbracket = "]";
static const char *key_name_caret = "^";
static const char *key_name_underscore = "_";
static const char *key_name_backquote = "`";
static const char *key_name_a = "A";
static const char *key_name_b = "B";
static const char *key_name_c = "C";
static const char *key_name_d = "D";
static const char *key_name_e = "E";
static const char *key_name_f = "F";
static const char *key_name_g = "G";
static const char *key_name_h = "H";
static const char *key_name_i = "I";
static const char *key_name_j = "J";
static const char *key_name_k = "K";
static const char *key_name_l = "L";
static const char *key_name_m = "M";
static const char *key_name_n = "N";
static const char *key_name_o = "O";
static const char *key_name_p = "P";
static const char *key_name_q = "Q";
static const char *key_name_r = "R";
static const char *key_name_s = "S";
static const char *key_name_t = "T";
static const char *key_name_u = "U";
static const char *key_name_v = "V";
static const char *key_name_w = "W";
static const char *key_name_x = "X";
static const char *key_name_y = "Y";
static const char *key_name_z = "Z";
static const char *key_name_delete = "Del";
static const char *key_name_world_0 = "World 0";
static const char *key_name_world_1 = "World_1";
static const char *key_name_world_2 = "World_2";
static const char *key_name_world_3 = "World_3";
static const char *key_name_world_4 = "World 4";
static const char *key_name_world_5 = "World 5";
static const char *key_name_world_6 = "World 6";
static const char *key_name_world_7 = "World 7";
static const char *key_name_world_8 = "World 8";
static const char *key_name_world_9 = "World 9";
static const char *key_name_world_10 = "World 10";
static const char *key_name_world_11 = "World 11";
static const char *key_name_world_12 = "World 12";
static const char *key_name_world_13 = "World 13";
static const char *key_name_world_14 = "World 14";
static const char *key_name_world_15 = "World 15";
static const char *key_name_world_16 = "World 16";
static const char *key_name_world_17 = "World 17";
static const char *key_name_world_18 = "World 18";
static const char *key_name_world_19 = "World 19";
static const char *key_name_world_20 = "World 20";
static const char *key_name_world_21 = "World 21";
static const char *key_name_world_22 = "World 22";
static const char *key_name_world_23 = "World 23";
static const char *key_name_world_24 = "World 24";
static const char *key_name_world_25 = "World 25";
static const char *key_name_world_26 = "World 26";
static const char *key_name_world_27 = "World 27";
static const char *key_name_world_28 = "World 28";
static const char *key_name_world_29 = "World 29";
static const char *key_name_world_30 = "World 30";
static const char *key_name_world_31 = "World 31";
static const char *key_name_world_32 = "World 32";
static const char *key_name_world_33 = "World 33";
static const char *key_name_world_34 = "World 34";
static const char *key_name_world_35 = "World 35";
static const char *key_name_world_36 = "World 36";
static const char *key_name_world_37 = "World 37";
static const char *key_name_world_38 = "World 38";
static const char *key_name_world_39 = "World 39";
static const char *key_name_world_40 = "World 40";
static const char *key_name_world_41 = "World 41";
static const char *key_name_world_42 = "World 42";
static const char *key_name_world_43 = "World 43";
static const char *key_name_world_44 = "World 44";
static const char *key_name_world_45 = "World 45";
static const char *key_name_world_46 = "World 46";
static const char *key_name_world_47 = "World 47";
static const char *key_name_world_48 = "World 48";
static const char *key_name_world_49 = "World 49";
static const char *key_name_world_50 = "World 50";
static const char *key_name_world_51 = "World 51";
static const char *key_name_world_52 = "World 52";
static const char *key_name_world_53 = "World 53";
static const char *key_name_world_54 = "World 54";
static const char *key_name_world_55 = "World 55";
static const char *key_name_world_56 = "World 56";
static const char *key_name_world_57 = "World 57";
static const char *key_name_world_58 = "World 58";
static const char *key_name_world_59 = "World 59";
static const char *key_name_world_60 = "World 60";
static const char *key_name_world_61 = "World 61";
static const char *key_name_world_62 = "World 62";
static const char *key_name_world_63 = "World 63";
static const char *key_name_world_64 = "World 64";
static const char *key_name_world_65 = "World 65";
static const char *key_name_world_66 = "World 66";
static const char *key_name_world_67 = "World 67";
static const char *key_name_world_68 = "World 68";
static const char *key_name_world_69 = "World 69";
static const char *key_name_world_70 = "World 70";
static const char *key_name_world_71 = "World 71";
static const char *key_name_world_72 = "World 72";
static const char *key_name_world_73 = "World 73";
static const char *key_name_world_74 = "World 74";
static const char *key_name_world_75 = "World 75";
static const char *key_name_world_76 = "World 76";
static const char *key_name_world_77 = "World 77";
static const char *key_name_world_78 = "World 78";
static const char *key_name_world_79 = "World 79";
static const char *key_name_world_80 = "World 80";
static const char *key_name_world_81 = "World 81";
static const char *key_name_world_82 = "World 82";
static const char *key_name_world_83 = "World 83";
static const char *key_name_world_84 = "World 84";
static const char *key_name_world_85 = "World 85";
static const char *key_name_world_86 = "World 86";
static const char *key_name_world_87 = "World 87";
static const char *key_name_world_88 = "World 88";
static const char *key_name_world_89 = "World 89";
static const char *key_name_world_90 = "World 90";
static const char *key_name_world_91 = "World 91";
static const char *key_name_world_92 = "World 92";
static const char *key_name_world_93 = "World 93";
static const char *key_name_world_94 = "World 94";
static const char *key_name_world_95 = "World 95";
static const char *key_name_kp0 = "Num0";
static const char *key_name_kp1 = "Num1";
static const char *key_name_kp2 = "Num2";
static const char *key_name_kp3 = "Num3";
static const char *key_name_kp4 = "Num4";
static const char *key_name_kp5 = "Num5";
static const char *key_name_kp6 = "Num6";
static const char *key_name_kp7 = "Num7";
static const char *key_name_kp8 = "Num8";
static const char *key_name_kp9 = "Num9";
static const char *key_name_kp_period = "Num.";
static const char *key_name_kp_divide = "Num/";
static const char *key_name_kp_multiply = "Num*";
static const char *key_name_kp_minus = "Num-";
static const char *key_name_kp_plus = "Num+";
static const char *key_name_kp_enter = "Num Enter";
static const char *key_name_kp_equals = "Num=";
static const char *key_name_up = "Up";
static const char *key_name_down = "Down";
static const char *key_name_right = "Right";
static const char *key_name_left = "Left";
static const char *key_name_insert = "Ins";
static const char *key_name_home = "Home";
static const char *key_name_end = "End";
static const char *key_name_pageup = "PgUp";
static const char *key_name_pagedown = "PgDn";
static const char *key_name_f1 = "F1";
static const char *key_name_f2 = "F2";
static const char *key_name_f3 = "F3";
static const char *key_name_f4 = "F4";
static const char *key_name_f5 = "F5";
static const char *key_name_f6 = "F6";
static const char *key_name_f7 = "F7";
static const char *key_name_f8 = "F8";
static const char *key_name_f9 = "F9";
static const char *key_name_f10 = "F10";
static const char *key_name_f11 = "F11";
static const char *key_name_f12 = "F12";
static const char *key_name_f13 = "F13";
static const char *key_name_f14 = "F14";
static const char *key_name_f15 = "F15";
static const char *key_name_numlock = "Numlock";
static const char *key_name_capslock = "Capslock";
static const char *key_name_scrollock = "Scrollock";
static const char *key_name_rshift = "RShift";
static const char *key_name_lshift = "LShift";
static const char *key_name_rctrl = "RCtrl";
static const char *key_name_lctrl = "LCtrl";
static const char *key_name_ralt = "RAlt";
static const char *key_name_lalt = "LAlt";
static const char *key_name_rmeta = "RMeta";
static const char *key_name_lmeta = "LMeta";
static const char *key_name_lsuper = "LSuper";
static const char *key_name_rsuper = "RSuper";
static const char *key_name_mode = "Mode";
static const char *key_name_compose = "Compose";
static const char *key_name_help = "Help";
static const char *key_name_print = "PrintScrn";
static const char *key_name_sysreq = "SysRq";
static const char *key_name_break = "Break";
static const char *key_name_menu = "Menu";
static const char *key_name_power = "Power";
static const char *key_name_euro = "Euro";
static const char *key_name_undo = "Undo";

const char *key_name( int key ) {
	switch( key ) {
		case SDLK_BACKSPACE: return key_name_backspace;
		case SDLK_TAB: return key_name_tab;
		case SDLK_CLEAR: return key_name_clear;
		case SDLK_RETURN: return key_name_return;
		case SDLK_PAUSE: return key_name_pause;
		case SDLK_ESCAPE: return key_name_escape;
		case SDLK_SPACE: return key_name_space;
		case SDLK_EXCLAIM: return key_name_exclaim;
		case SDLK_QUOTEDBL: return key_name_quotedbl;
		case SDLK_HASH: return key_name_hash;
		case SDLK_DOLLAR: return key_name_dollar;
		case SDLK_AMPERSAND: return key_name_ampersand;
		case SDLK_QUOTE: return key_name_quote;
		case SDLK_LEFTPAREN: return key_name_leftparen;
		case SDLK_RIGHTPAREN: return key_name_rightparen;
		case SDLK_ASTERISK: return key_name_asterisk;
		case SDLK_PLUS: return key_name_plus;
		case SDLK_COMMA: return key_name_comma;
		case SDLK_MINUS: return key_name_minus;
		case SDLK_PERIOD: return key_name_period;
		case SDLK_SLASH: return key_name_slash;
		case SDLK_0: return key_name_0;
		case SDLK_1: return key_name_1;
		case SDLK_2: return key_name_2;
		case SDLK_3: return key_name_3;
		case SDLK_4: return key_name_4;
		case SDLK_5: return key_name_5;
		case SDLK_6: return key_name_6;
		case SDLK_7: return key_name_7;
		case SDLK_8: return key_name_8;
		case SDLK_9: return key_name_9;
		case SDLK_COLON: return key_name_colon;
		case SDLK_SEMICOLON: return key_name_semicolon;
		case SDLK_LESS: return key_name_less;
		case SDLK_EQUALS: return key_name_equals;
		case SDLK_GREATER: return key_name_greater;
		case SDLK_QUESTION: return key_name_question;
		case SDLK_AT: return key_name_at;
		case SDLK_LEFTBRACKET: return key_name_leftbracket;
		case SDLK_BACKSLASH: return key_name_backslash;
		case SDLK_RIGHTBRACKET: return key_name_rightbracket;
		case SDLK_CARET: return key_name_caret;
		case SDLK_UNDERSCORE: return key_name_underscore;
		case SDLK_BACKQUOTE: return key_name_backquote;
		case SDLK_a: return key_name_a;
		case SDLK_b: return key_name_b;
		case SDLK_c: return key_name_c;
		case SDLK_d: return key_name_d;
		case SDLK_e: return key_name_e;
		case SDLK_f: return key_name_f;
		case SDLK_g: return key_name_g;
		case SDLK_h: return key_name_h;
		case SDLK_i: return key_name_i;
		case SDLK_j: return key_name_j;
		case SDLK_k: return key_name_k;
		case SDLK_l: return key_name_l;
		case SDLK_m: return key_name_m;
		case SDLK_n: return key_name_n;
		case SDLK_o: return key_name_o;
		case SDLK_p: return key_name_p;
		case SDLK_q: return key_name_q;
		case SDLK_r: return key_name_r;
		case SDLK_s: return key_name_s;
		case SDLK_t: return key_name_t;
		case SDLK_u: return key_name_u;
		case SDLK_v: return key_name_v;
		case SDLK_w: return key_name_w;
		case SDLK_x: return key_name_x;
		case SDLK_y: return key_name_y;
		case SDLK_z: return key_name_z;
		case SDLK_DELETE: return key_name_delete;
		case SDLK_WORLD_0: return key_name_world_0;
		case SDLK_WORLD_1: return key_name_world_1;
		case SDLK_WORLD_2: return key_name_world_2;
		case SDLK_WORLD_3: return key_name_world_3;
		case SDLK_WORLD_4: return key_name_world_4;
		case SDLK_WORLD_5: return key_name_world_5;
		case SDLK_WORLD_6: return key_name_world_6;
		case SDLK_WORLD_7: return key_name_world_7;
		case SDLK_WORLD_8: return key_name_world_8;
		case SDLK_WORLD_9: return key_name_world_9;
		case SDLK_WORLD_10: return key_name_world_10;
		case SDLK_WORLD_11: return key_name_world_11;
		case SDLK_WORLD_12: return key_name_world_12;
		case SDLK_WORLD_13: return key_name_world_13;
		case SDLK_WORLD_14: return key_name_world_14;
		case SDLK_WORLD_15: return key_name_world_15;
		case SDLK_WORLD_16: return key_name_world_16;
		case SDLK_WORLD_17: return key_name_world_17;
		case SDLK_WORLD_18: return key_name_world_18;
		case SDLK_WORLD_19: return key_name_world_19;
		case SDLK_WORLD_20: return key_name_world_20;
		case SDLK_WORLD_21: return key_name_world_21;
		case SDLK_WORLD_22: return key_name_world_22;
		case SDLK_WORLD_23: return key_name_world_23;
		case SDLK_WORLD_24: return key_name_world_24;
		case SDLK_WORLD_25: return key_name_world_25;
		case SDLK_WORLD_26: return key_name_world_26;
		case SDLK_WORLD_27: return key_name_world_27;
		case SDLK_WORLD_28: return key_name_world_28;
		case SDLK_WORLD_29: return key_name_world_29;
		case SDLK_WORLD_30: return key_name_world_30;
		case SDLK_WORLD_31: return key_name_world_31;
		case SDLK_WORLD_32: return key_name_world_32;
		case SDLK_WORLD_33: return key_name_world_33;
		case SDLK_WORLD_34: return key_name_world_34;
		case SDLK_WORLD_35: return key_name_world_35;
		case SDLK_WORLD_36: return key_name_world_36;
		case SDLK_WORLD_37: return key_name_world_37;
		case SDLK_WORLD_38: return key_name_world_38;
		case SDLK_WORLD_39: return key_name_world_39;
		case SDLK_WORLD_40: return key_name_world_40;
		case SDLK_WORLD_41: return key_name_world_41;
		case SDLK_WORLD_42: return key_name_world_42;
		case SDLK_WORLD_43: return key_name_world_43;
		case SDLK_WORLD_44: return key_name_world_44;
		case SDLK_WORLD_45: return key_name_world_45;
		case SDLK_WORLD_46: return key_name_world_46;
		case SDLK_WORLD_47: return key_name_world_47;
		case SDLK_WORLD_48: return key_name_world_48;
		case SDLK_WORLD_49: return key_name_world_49;
		case SDLK_WORLD_50: return key_name_world_50;
		case SDLK_WORLD_51: return key_name_world_51;
		case SDLK_WORLD_52: return key_name_world_52;
		case SDLK_WORLD_53: return key_name_world_53;
		case SDLK_WORLD_54: return key_name_world_54;
		case SDLK_WORLD_55: return key_name_world_55;
		case SDLK_WORLD_56: return key_name_world_56;
		case SDLK_WORLD_57: return key_name_world_57;
		case SDLK_WORLD_58: return key_name_world_58;
		case SDLK_WORLD_59: return key_name_world_59;
		case SDLK_WORLD_60: return key_name_world_60;
		case SDLK_WORLD_61: return key_name_world_61;
		case SDLK_WORLD_62: return key_name_world_62;
		case SDLK_WORLD_63: return key_name_world_63;
		case SDLK_WORLD_64: return key_name_world_64;
		case SDLK_WORLD_65: return key_name_world_65;
		case SDLK_WORLD_66: return key_name_world_66;
		case SDLK_WORLD_67: return key_name_world_67;
		case SDLK_WORLD_68: return key_name_world_68;
		case SDLK_WORLD_69: return key_name_world_69;
		case SDLK_WORLD_70: return key_name_world_70;
		case SDLK_WORLD_71: return key_name_world_71;
		case SDLK_WORLD_72: return key_name_world_72;
		case SDLK_WORLD_73: return key_name_world_73;
		case SDLK_WORLD_74: return key_name_world_74;
		case SDLK_WORLD_75: return key_name_world_75;
		case SDLK_WORLD_76: return key_name_world_76;
		case SDLK_WORLD_77: return key_name_world_77;
		case SDLK_WORLD_78: return key_name_world_78;
		case SDLK_WORLD_79: return key_name_world_79;
		case SDLK_WORLD_80: return key_name_world_80;
		case SDLK_WORLD_81: return key_name_world_81;
		case SDLK_WORLD_82: return key_name_world_82;
		case SDLK_WORLD_83: return key_name_world_83;
		case SDLK_WORLD_84: return key_name_world_84;
		case SDLK_WORLD_85: return key_name_world_85;
		case SDLK_WORLD_86: return key_name_world_86;
		case SDLK_WORLD_87: return key_name_world_87;
		case SDLK_WORLD_88: return key_name_world_88;
		case SDLK_WORLD_89: return key_name_world_89;
		case SDLK_WORLD_90: return key_name_world_90;
		case SDLK_WORLD_91: return key_name_world_91;
		case SDLK_WORLD_92: return key_name_world_92;
		case SDLK_WORLD_93: return key_name_world_93;
		case SDLK_WORLD_94: return key_name_world_94;
		case SDLK_WORLD_95: return key_name_world_95;
		case SDLK_KP0: return key_name_kp0;
		case SDLK_KP1: return key_name_kp1;
		case SDLK_KP2: return key_name_kp2;
		case SDLK_KP3: return key_name_kp3;
		case SDLK_KP4: return key_name_kp4;
		case SDLK_KP5: return key_name_kp5;
		case SDLK_KP6: return key_name_kp6;
		case SDLK_KP7: return key_name_kp7;
		case SDLK_KP8: return key_name_kp8;
		case SDLK_KP9: return key_name_kp9;
		case SDLK_KP_PERIOD: return key_name_kp_period;
		case SDLK_KP_DIVIDE: return key_name_kp_divide;
		case SDLK_KP_MULTIPLY: return key_name_kp_multiply;
		case SDLK_KP_MINUS: return key_name_kp_minus;
		case SDLK_KP_PLUS: return key_name_kp_plus;
		case SDLK_KP_ENTER: return key_name_kp_enter;
		case SDLK_KP_EQUALS: return key_name_kp_equals;
		case SDLK_UP: return key_name_up;
		case SDLK_DOWN: return key_name_down;
		case SDLK_RIGHT: return key_name_right;
		case SDLK_LEFT: return key_name_left;
		case SDLK_INSERT: return key_name_insert;
		case SDLK_HOME: return key_name_home;
		case SDLK_END: return key_name_end;
		case SDLK_PAGEUP: return key_name_pageup;
		case SDLK_PAGEDOWN: return key_name_pagedown;
		case SDLK_F1: return key_name_f1;
		case SDLK_F2: return key_name_f2;
		case SDLK_F3: return key_name_f3;
		case SDLK_F4: return key_name_f4;
		case SDLK_F5: return key_name_f5;
		case SDLK_F6: return key_name_f6;
		case SDLK_F7: return key_name_f7;
		case SDLK_F8: return key_name_f8;
		case SDLK_F9: return key_name_f9;
		case SDLK_F10: return key_name_f10;
		case SDLK_F11: return key_name_f11;
		case SDLK_F12: return key_name_f12;
		case SDLK_F13: return key_name_f13;
		case SDLK_F14: return key_name_f14;
		case SDLK_F15: return key_name_f15;
		case SDLK_NUMLOCK: return key_name_numlock;
		case SDLK_CAPSLOCK: return key_name_capslock;
		case SDLK_SCROLLOCK: return key_name_scrollock;
		case SDLK_RSHIFT: return key_name_rshift;
		case SDLK_LSHIFT: return key_name_lshift;
		case SDLK_RCTRL: return key_name_rctrl;
		case SDLK_LCTRL: return key_name_lctrl;
		case SDLK_RALT: return key_name_ralt;
		case SDLK_LALT: return key_name_lalt;
		case SDLK_RMETA: return key_name_rmeta;
		case SDLK_LMETA: return key_name_lmeta;
		case SDLK_LSUPER: return key_name_lsuper;
		case SDLK_RSUPER: return key_name_rsuper;
		case SDLK_MODE: return key_name_mode;
		case SDLK_COMPOSE: return key_name_compose;
		case SDLK_HELP: return key_name_help;
		case SDLK_PRINT: return key_name_print;
		case SDLK_SYSREQ: return key_name_sysreq;
		case SDLK_BREAK: return key_name_break;
		case SDLK_MENU: return key_name_menu;
		case SDLK_POWER: return key_name_power;
		case SDLK_EURO: return key_name_euro;
		case SDLK_UNDO: return key_name_undo;
	}
	return NULL;
}

